// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDropdown: typeof import('./src/components/BaseDropdown.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseTooltip: typeof import('./src/components/BaseTooltip.vue')['default']
    CardHole: typeof import('./src/components/CardHole.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheSettings: typeof import('./src/components/TheSettings.vue')['default']
  }
}

export {}
